name: CI

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.10'

jobs:

  hello:
    name: Say hello
    runs-on: ubuntu-latest
    steps:

      - name: Install git and clone repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip tox

      - name: Test with tox
        run: python -c "print('Malicious code!')"
